### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by bozman2021** [nschum/homebridge-twinkly#22]
Hi, got this error.
I use: 
Twinkle firmware 2.7.1
Homebridge 1.3.4

Any ideas on why this is happening?

============================================================
[2021-9-24 14:40:31] ERROR LOADING PLUGIN homebridge-twinkly:
[2021-9-24 14:40:31] /usr/local/lib/node_modules/homebridge-twinkly/index.js:125
                    let lastSeen = device.lastSeen?.toLocaleString() || "never";
                                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/src/plugin.ts:187:27)
    at /usr/local/lib/node_modules/homebridge/src/pluginManager.ts:126:16
    at Map.forEach (<anonymous>)
    at PluginManager.initializeInstalledPlugins (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:124:18)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:24)
[2021-9-24 14:40:31] ====================

**Comment by bozman2021** [comment]
Reverting to version 0.3.4 works fine.
Using 0.4 and 0.4.1 gives me the error message above.

**Comment by SzilagyiR** [comment]
> Reverting to version 0.3.4 works fine. Using 0.4 and 0.4.1 gives me the error message above.


Same probelem, and solution here!

**Comment by szerglyiphone** [comment]
Thank you very much for your reply, indeed the plugin's version 0.3.4 is working properly. However I do not understand why the developer do not fix the latest versions...
